name: flutter_timetable_view_demo
description: A Demo Application of Flutter Timetable View
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.7.12"

dependencies:
  flutter:
    sdk: flutter
  # flutter_timetable_view: ^0.2.0
  timetable_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true