name: timetable_view
description: Timetable Widget Package for for Flutter. Fork from @Matt0550
version: 0.3.0+6
homepage: https://github.com/Matt0550

environment:
  sdk: '>=2.17.6 <3.7.12'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
